"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { t, useLanguage } from "@/lib/i18n";

export default function SetupForm() {
  const language = useLanguage();
  const router = useRouter(); const [subject, setSubject] = useState(""); const [assignment, setAssignment] = useState(""); const [submission, setSubmission] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  function tryExample() { setSubject(language === "kk" ? "Биология" : language === "ru" ? "Биология" : "Biology"); setAssignment(language === "kk" ? "Табиғи сұрыпталу популяцияны уақыт өте қалай өзгерте алатынын түсіндіріңіз. Өзгергіштік, тұқымқуалау және орта қысымының рөлін қосыңыз." : language === "ru" ? "Объясните, как естественный отбор может изменить популяцию со временем. Раскройте роль изменчивости, наследования и давления среды." : "Explain how natural selection can change a population over time. Include the role of variation, inheritance, and environmental pressure."); setSubmission(language === "kk" ? "Табиғи сұрыпталу пайдалы белгілері бар ағзалар жақсырақ тірі қалып, көбірек ұрпақ қалдырғанда жүреді. Бұл белгілер тұқым қуалайтындықтан, кейінгі ұрпақтарда жиірек кездеседі. Мысалы, жақсы жасырынатын қоңыздарды жыртқыштар аз жейді, сондықтан бұл белгі популяцияда таралуы мүмкін." : language === "ru" ? "Естественный отбор происходит, когда организмы с полезными признаками лучше выживают и оставляют больше потомства. Эти признаки становятся чаще в следующих поколениях, потому что передаются по наследству. Например, хорошо замаскированных жуков хищники едят реже, поэтому признак маскировки может распространиться в популяции." : "Natural selection occurs when organisms with useful traits survive and reproduce more successfully. These traits become more common in later generations because they are inherited. For example, if some beetles are better camouflaged, predators are less likely to eat them, so the camouflage trait can spread through the population over time."); setError(""); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/structure", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject, assignment, submission, language }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); sessionStorage.setItem("prooflearn", JSON.stringify({ subject, assignment, submission, language, ...data, currentQuestion: data.firstQuestion, history: [], evaluations: [], questionNumber: 1, draftAnswer: "" })); router.push("/verify"); } catch (e) { setError(e instanceof Error ? e.message : t(language, "error")); setLoading(false); } }
  return <form className="setup-form" onSubmit={submit}><div className="form-heading"><span>{t(language, "inputWork")}</span><button type="button" className="text-button" onClick={tryExample}>{t(language, "tryExample")}</button></div><label>{t(language, "subject")}<input required value={subject} onChange={e => setSubject(e.target.value)} placeholder={t(language, "subjectPlaceholder")} /></label><label>{t(language, "assignment")}<textarea required value={assignment} onChange={e => setAssignment(e.target.value)} placeholder={t(language, "assignmentPlaceholder")} rows={4} /></label><label>{t(language, "submission")}<textarea required value={submission} onChange={e => setSubmission(e.target.value)} placeholder={t(language, "submissionPlaceholder")} rows={7} /></label>{error && <p className="error">{error}</p>}<button className="button primary" disabled={loading}>{loading ? <><span className="dot" /> {t(language, "analysing")}</> : <>{t(language, "generate")} <span>→</span></>}</button></form>;
}
