"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Session = { subject:string; assignment:string; submission:string; conceptMap: unknown; firstQuestion:string; history:{question:string;answer:string}[]; updates:Record<string,number>[]; questionNumber:number };
export default function VerifyClient() { const router = useRouter(); const [data, setData] = useState<Session | null>(null); const [answer, setAnswer] = useState(""); const [question, setQuestion] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const raw = sessionStorage.getItem("prooflearn"); if (raw) { const parsed = JSON.parse(raw); setData(parsed); setQuestion(parsed.firstQuestion); } }, []);
  if (!data) return <div className="loading-block">Loading your verification…</div>;
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!answer.trim()) return; setLoading(true); setError(""); const history = [...data!.history, { question, answer }]; try { const response = await fetch("/api/evaluate", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ subject:data!.subject, assignment:data!.assignment, submission:data!.submission, conceptMap:data!.conceptMap, history:data!.history, latestAnswer:answer, currentQuestion:question }) }); const evaluation = await response.json(); if (!response.ok) throw new Error(evaluation.error); const next = { ...data!, history, updates:[...data!.updates, evaluation.mastery_updates], questionNumber:data!.questionNumber + 1 }; if (next.questionNumber > 4) { const reportResponse = await fetch("/api/report", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ conceptMap:next.conceptMap, history, updates:next.updates }) }); const report = await reportResponse.json(); if (!reportResponse.ok) throw new Error(report.error); sessionStorage.setItem("prooflearn-report", JSON.stringify(report)); router.push("/report"); } else { setData(next); setQuestion(evaluation.next_question); setAnswer(""); sessionStorage.setItem("prooflearn", JSON.stringify(next)); } } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong"); } finally { setLoading(false); } }
  return <div className="verify-wrap"><div className="verify-meta"><p className="eyebrow">Adaptive defence / {data.subject}</p><span>Question {data.questionNumber} of ~4</span></div><div className="progress"><div style={{width:`${Math.min(data.questionNumber / 4 * 100, 100)}%`}} /></div><section className="question-area"><p className="question-label">Your question</p><h1>{question}</h1><form onSubmit={submit}><label>Your answer<textarea autoFocus required value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Think it through, then explain it in your own words…" rows={7} /></label>{error && <p className="error">{error}</p>}<button className="button primary" disabled={loading}>{loading ? <><span className="dot" /> Evaluating answer…</> : <>Submit Answer <span>→</span></>}</button></form></section></div>;
}
