"use client";

import { useEffect, useState } from "react";

export type Language = "en" | "ru" | "kk";

export const languageNames: Record<Language, string> = { en: "English", ru: "Русский", kk: "Қазақша" };

const translations: Record<Language, Record<string, string>> = {
  en: {
    landingEyebrow: "A short text-based defence", landingHeadline: "Verify understanding,|not authorship.", landingLede: "Turn any student submission into a personalized short text-based defence.", create: "Create verification", notDetector: "We don't detect AI. We verify learning.", assessment: "Assessment, rethought", stage: "01 / 03", setupEyebrow: "Create verification", setupTitle: "Start with the|student's work.", setupIntro: "Give us the prompt and the answer. We'll build a focused defence around what the student actually wrote.", inputWork: "Input the work to check", tryExample: "Try an example", subject: "Subject", assignment: "Assignment", submission: "Student submission", subjectPlaceholder: "e.g. Biology", assignmentPlaceholder: "The question or prompt given to the student…", submissionPlaceholder: "Paste the student's answer here…", generate: "Generate verification", analysing: "Analysing submission…", questionStage: "02 / 03", shortDefence: "Short text defence", question: "Question", yourQuestion: "Your question", yourAnswer: "Your answer", answerPlaceholder: "Explain it in your own words…", submitAnswer: "Submit answer", evaluating: "Evaluating answer…", restoring: "Restoring your verification…", reportStage: "03 / 03", complete: "Verification complete", completeTitle: "Verification|Complete.", overall: "Overall understanding", preliminary: "A preliminary score based only on concepts checked during this defence.", conceptMastery: "Concept mastery", conceptsRubric: "concepts in the rubric", strong: "Strong understanding", improvement: "Needs improvement", misconception: "Detected misconception", noMisconception: "No clear misconception was identified during this defence.", nextStep: "Recommended next step", viewAnswers: "View answers", newVerification: "New verification", evidence: "Evidence", why: "Why", next: "Next", noEvidence: "No direct evidence recorded.", insufficient: "Insufficient data", rubricNote: "Preliminary evidence from this defence. Final judgement remains with the teacher.", answerLabel: "Question", noStrong: "No concepts reached strong evidence yet.", noWeak: "No immediate gaps identified.", loadingReport: "Preparing your report…", step: "Step", persists: "Persists", corrected: "Corrected after clarification", needsCheck: "Needs another check", noIssue: "No issue detected", questionOf: "of ~4", error: "Something went wrong", marginStructure: "Structure|the answer.", marginTest: "Test the|understanding.", marginSub: "Concepts, claims,|reasoning.", marginOne: "One answer at|a time.", reportFraming: "ProofLearn found evidence of approximately {score}% mastery across the concepts tested during this verification." },
  ru: {
    landingEyebrow: "Короткая текстовая защита", landingHeadline: "Проверяем понимание,|а не авторство.", landingLede: "Превратите ответ ученика в персональную короткую текстовую защиту.", create: "Создать проверку", notDetector: "Мы не ищем ИИ. Мы проверяем понимание.", assessment: "Переосмысливаем оценивание", stage: "01 / 03", setupEyebrow: "Создание проверки", setupTitle: "Начнём с|работы ученика.", setupIntro: "Дайте задание и ответ. Мы построим проверку вокруг того, что ученик действительно написал.", inputWork: "Данные для проверки", tryExample: "Попробовать пример", subject: "Предмет", assignment: "Задание", submission: "Ответ ученика", subjectPlaceholder: "Например, биология", assignmentPlaceholder: "Вопрос или задание для ученика…", submissionPlaceholder: "Вставьте ответ ученика…", generate: "Создать проверку", analysing: "Анализируем ответ…", questionStage: "02 / 03", shortDefence: "Короткая текстовая защита", question: "Вопрос", yourQuestion: "Ваш вопрос", yourAnswer: "Ваш ответ", answerPlaceholder: "Объясните своими словами…", submitAnswer: "Отправить ответ", evaluating: "Оцениваем ответ…", restoring: "Восстанавливаем проверку…", reportStage: "03 / 03", complete: "Проверка завершена", completeTitle: "Проверка|завершена.", overall: "Общее понимание", preliminary: "Предварительная оценка только проверенных в этой защите понятий.", conceptMastery: "Понимание концепций", conceptsRubric: "концепций в рубрике", strong: "Уверенное понимание", improvement: "Нужно улучшить", misconception: "Обнаруженное заблуждение", noMisconception: "Явного заблуждения в этой защите не обнаружено.", nextStep: "Рекомендуемый следующий шаг", viewAnswers: "Посмотреть ответы", newVerification: "Новая проверка", evidence: "Доказательство", why: "Почему", next: "Дальше", noEvidence: "Прямое доказательство не записано.", insufficient: "Недостаточно данных", rubricNote: "Предварительные данные этой защиты. Итоговое решение принимает учитель.", answerLabel: "Вопрос", noStrong: "Пока нет понятий с уверенным пониманием.", noWeak: "Немедленных пробелов не обнаружено.", loadingReport: "Готовим отчёт…", step: "Этап", persists: "Сохраняется", corrected: "Исправлено после уточнения", needsCheck: "Нужно проверить ещё", noIssue: "Проблема не обнаружена", questionOf: "из ~4", error: "Что-то пошло не так", marginStructure: "Структурируем|ответ.", marginTest: "Проверяем|понимание.", marginSub: "Концепции, утверждения,|логика.", marginOne: "Один ответ|за раз.", reportFraming: "ProofLearn нашёл примерно {score}% признаков понимания среди проверенных в этой защите." },
  kk: {
    landingEyebrow: "Қысқа мәтіндік қорғау", landingHeadline: "Түсінуді тексереміз,|авторлықты емес.", landingLede: "Оқушы жауабын жеке қысқа мәтіндік қорғауға айналдырыңыз.", create: "Тексеру жасау", notDetector: "Біз ЖИ-ді анықтамаймыз. Біз түсінуді тексереміз.", assessment: "Бағалауды қайта ойлау", stage: "01 / 03", setupEyebrow: "Тексеру жасау", setupTitle: "Оқушының|жұмысынан бастайық.", setupIntro: "Тапсырма мен жауапты беріңіз. Біз тек оқушы жазған жұмысқа сүйенген тексеру құрамыз.", inputWork: "Тексерілетін жұмыс", tryExample: "Мысалды көру", subject: "Пән", assignment: "Тапсырма", submission: "Оқушының жауабы", subjectPlaceholder: "Мысалы, биология", assignmentPlaceholder: "Оқушыға берілген сұрақ немесе тапсырма…", submissionPlaceholder: "Оқушының жауабын енгізіңіз…", generate: "Тексеру жасау", analysing: "Жауап талдануда…", questionStage: "02 / 03", shortDefence: "Қысқа мәтіндік қорғау", question: "Сұрақ", yourQuestion: "Сіздің сұрағыңыз", yourAnswer: "Сіздің жауабыңыз", answerPlaceholder: "Өз сөзіңізбен түсіндіріңіз…", submitAnswer: "Жауапты жіберу", evaluating: "Жауап бағалануда…", restoring: "Тексеру қалпына келтірілуде…", reportStage: "03 / 03", complete: "Тексеру аяқталды", completeTitle: "Тексеру|аяқталды.", overall: "Жалпы түсіну", preliminary: "Бұл қорғауда тексерілген түсініктерге арналған алдын ала баға.", conceptMastery: "Түсініктерді меңгеру", conceptsRubric: "түсінік рубрикада", strong: "Жақсы түсіну", improvement: "Жақсарту қажет", misconception: "Анықталған қате түсінік", noMisconception: "Бұл қорғауда анық қате түсінік табылмады.", nextStep: "Ұсынылатын келесі қадам", viewAnswers: "Жауаптарды көру", newVerification: "Жаңа тексеру", evidence: "Дәлел", why: "Неге", next: "Келесі қадам", noEvidence: "Тікелей дәлел жазылмаған.", insufficient: "Дерек жеткіліксіз", rubricNote: "Бұл қорғаудың алдын ала деректері. Соңғы шешімді мұғалім қабылдайды.", answerLabel: "Сұрақ", noStrong: "Әзірге толық меңгерілген түсініктер жоқ.", noWeak: "Шұғыл кемшіліктер анықталмады.", loadingReport: "Есеп дайындалуда…", step: "Кезең", persists: "Сақталды", corrected: "Түсіндіруден кейін түзетілді", needsCheck: "Қайта тексеру қажет", noIssue: "Мәселе анықталмады", questionOf: "~4 ішінен", error: "Қате пайда болды", marginStructure: "Жауапты|құрылымдаймыз.", marginTest: "Түсінуді|тексереміз.", marginSub: "Түсініктер, пікірлер,|логика.", marginOne: "Бір жауап|бір уақытта.", reportFraming: "ProofLearn осы қорғауда тексерілген түсініктер бойынша шамамен {score}% түсіну дәлелін тапты." },
};

export function t(language: Language, key: string) { return translations[language]?.[key] || translations.en[key] || key; }

export function useLanguage() {
  const [language, setLanguage] = useState<Language>("en");
  useEffect(() => {
    const saved = localStorage.getItem("prooflearn-language") as Language | null;
    if (saved && saved in languageNames) setLanguage(saved);
    const update = () => setLanguage((localStorage.getItem("prooflearn-language") as Language) || "en");
    window.addEventListener("prooflearn-language-change", update);
    return () => window.removeEventListener("prooflearn-language-change", update);
  }, []);
  return language;
}
